version: 2
updates:
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'test'
    ignore:
      - dependency-name: 'requests'
      - dependency-name: 'yt-dlp'
